FROM python:3.10-slim

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /app

RUN apt-get update && apt-get install -y \
    git \
    curl \
    wget \
    build-essential \
    libgl1-mesa-glx \
    nano \
    && rm -rf /var/lib/apt/lists/*

RUN useradd -ms /bin/bash appuser && \
    chown -R appuser /app

COPY --chown=appuser requirements.txt ./
RUN pip install --upgrade pip && pip install -r requirements.txt

COPY --chown=appuser data_loader/ ./data_loader/
RUN python data_loader/data_load.py

COPY --chown=appuser src/ ./src/

CMD ["python", "data_loader/data_load.py", "bash"]