version: "3.9"

services:
  iris:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    working_dir: /app
    command: >
      sh -c "
        pip install -e . &&
        pip install -r requirements.txt &&
        cron &&
        python rest_api/app.py
      "